name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.407
      - name: Setup dotnet tools
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet restore
      - name: Check formatting
        run: dotnet fantomas -r --check .
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: ./test.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.lcov
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
